INCLUDES = -I../UsageEnvironment/include -I../groupsock/include -I../liveMedia/include -I../BasicUsageEnvironment/include -I../AFDRTSP 
PTHREAD = -pthread 
##### Change the following for your environment: 
